# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

includes:
  - from_file:
      path: release/.goreleaser.base.edge-cli.yaml

cloudsmiths:
  - organization: malbeclabs
    repository: doublezero
    ids:
      - doublezero-edge
    distributions:
      deb: "any-distro/any-version"
      rpm: "any-distro/any-version"
